# This is a config for E2B sandbox template.
# You can use template ID (c08iqwboud8od1v5o7ab) or template name (uside-vibe-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("uside-vibe-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("uside-vibe-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('uside-vibe-test-2')

team_id = "83f3737b-b1e9-408d-9aad-6ecd42cfaff0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "uside-vibe-test-2"
template_id = "c08iqwboud8od1v5o7ab"
